# Generated by Django 5.2.15 on 2026-07-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningtax', '0002_delete_characterlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'general',
                'verbose_name_plural': 'general',
                'permissions': (('basic_access', 'Can view Mining Tax'), ('mining_officer', 'Can manage Mining Tax')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='alliancebillingrecord',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='alliancemoon',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='fleetsession',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='miningledgerentry',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='moonrental',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='orecategory',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'default_permissions': ()},
        ),
    ]
