# Generated by Django 5.2.15 on 2026-07-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miningtax', '0003_general_alter_alliancebillingrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can view Mining Tax'), ('mining_officer', 'Can manage Mining Tax'), ('no_access', 'Cannot access Mining Tax')), 'verbose_name': 'general', 'verbose_name_plural': 'general'},
        ),
    ]
