# Generated by Django 5.2.15 on 2026-07-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miningtax', '0004_alter_general_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can view Mining Tax'), ('mining_officer', 'Can manage Mining Tax')), 'verbose_name': 'general', 'verbose_name_plural': 'general'},
        ),
    ]
