# Generated by Django 5.2.15 on 2026-07-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('miningtax', '0005_alter_general_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='miningledgerentry',
            unique_together={('character', 'date', 'type_id')},
        ),
    ]
