# Generated by Django 5.2.15 on 2026-07-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('miningtax', '0006_alter_miningledgerentry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancebillingrecord',
            name='auto_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TreasuryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reason_keyword', models.CharField(default='Corp Steuer', help_text='Text der im Wallet-Journal-Grund enthalten sein muss (z.B. "Corp Steuer")', max_length=255)),
                ('wallet_division', models.PositiveSmallIntegerField(default=1, help_text='Wallet-Division die geprüft wird (1-7, Standard: 1 = Master Wallet)')),
                ('active', models.BooleanField(default=True)),
                ('corporation', models.ForeignKey(help_text='Corp deren Wallet auf eingehende Steuerzahlungen geprüft wird', on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporationinfo')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
