# Generated by Django 5.2.15 on 2026-07-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('miningtax', '0007_alliancebillingrecord_auto_verified_treasuryconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moonrental',
            name='corporation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miningtax_moon_rentals', to='eveonline.evecorporationinfo'),
        ),
        migrations.AlterField(
            model_name='treasuryconfig',
            name='corporation',
            field=models.ForeignKey(help_text='Corporation whose wallet is checked for incoming tax payments', on_delete=django.db.models.deletion.CASCADE, related_name='miningtax_treasury_configs', to='eveonline.evecorporationinfo'),
        ),
        migrations.AlterField(
            model_name='treasuryconfig',
            name='payment_reason_keyword',
            field=models.CharField(default='Corp Tax', help_text='Text that must be present in the wallet journal reason (e.g. "Corp Tax")', max_length=255),
        ),
        migrations.AlterField(
            model_name='treasuryconfig',
            name='wallet_division',
            field=models.PositiveSmallIntegerField(default=1, help_text='Wallet division to check (1-7, default: 1 = master wallet)'),
        ),
    ]
