# Generated by Django 5.2.15 on 2026-07-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miningtax', '0008_alter_moonrental_corporation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can view Mining Tax'), ('mining_officer', 'Can access Alliance Billing and Settings (Mining Officer)')), 'verbose_name': 'general', 'verbose_name_plural': 'general'},
        ),
    ]
