# Generated by Django 5.2.15 on 2026-07-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('miningtax', '0009_alter_general_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovSystem',
            fields=[
                ('system_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=255)),
                ('corporation_id', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='treasuryconfig',
            name='payment_reason_keyword',
            field=models.CharField(default='Corp Tax', help_text='Legacy field, no longer used for matching (kept for backward compatibility)', max_length=255),
        ),
        migrations.CreateModel(
            name='SovFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('corporation', models.ForeignKey(help_text="Only mining within this corporation's current sovereignty systems is taxed", on_delete=django.db.models.deletion.CASCADE, related_name='miningtax_sov_filter_configs', to='eveonline.evecorporationinfo')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
